# https://hub.docker.com/_/microsoft-dotnet-sdk/
FROM mcr.microsoft.com/dotnet/sdk:6.0.301-alpine3.16 AS build
WORKDIR /app

# Label as build image
LABEL "build"="xbee2mqtt"

# copy everything else and build
COPY ./ ./
WORKDIR /app
RUN dotnet restore .
RUN dotnet publish -c Release -o out

# https://hub.docker.com/_/microsoft-dotnet-runtime/
FROM mcr.microsoft.com/dotnet/runtime:6.0.6-alpine3.16 AS runtime
WORKDIR /app
COPY --from=build /app/out ./

ENTRYPOINT ["dotnet", "xbee2mqtt.dll"]